require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

install! 'cocoapods',
         :deterministic_uuids => false
         
target 'ShopsolWesop' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  pod 'react-native-contacts', :path => '../node_modules/react-native-contacts'
  pod 'RNFirebase', :path => '../node_modules/react-native-firebase/ios'
  pod 'react-native-date-picker', :path => '../node_modules/react-native-date-picker'
  
  pod 'react-native-maps', path: '../node_modules/react-native-maps'
  pod 'react-native-google-maps', path: '../node_modules/react-native-maps' 
  pod 'GoogleMaps' 
  pod 'Google-Maps-iOS-Utils'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics' 
  pod 'Firebase/Messaging'
  pod 'CodePush', :path => '../node_modules/react-native-code-push'

  target 'ShopsolWesopTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
  end
end

# target 'ShopsolWesop-tvOS' do
#   # Pods for ShopsolWesop-tvOS

#   target 'ShopsolWesop-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
# end

