[
  {
    message: 'SUCCESS',
    result: {
      Annual: '10',
      Annual_START: '2021',
      BONUS: '0',
      CALENDAR: '0',
      CalendarEdit: '1',
      EMP_NAME: '김규한',
      EMP_SEQ: '7887',
      END: null,
      FIRST: '0',
      INCENTIVE: '0',
      IS_MANAGER: '1',
      MEALS: '0',
      MEMBER_SEQ: '11825',
      MONTH: '',
      MobileNo: '01039308611',
      NEW_PAY: '0',
      NEW_PAY_SETTING: '0',
      OTHERPAY_SHOW: '1',
      PAY: '11112',
      PAY_SHOW: '1',
      PAY_START: '2021-01-01',
      PAY_TYPE: '1',
      PUSH: '1',
      REST_ALLOWANCE: '0',
      RemainderAnnual: '8',
      RestTime: '22',
      RestType: '0',
      SELF_DRIVING: '0',
      START: '2021-01-01',
      STOREPAY_SHOW: '1',
      STORE_SEQ: '6098',
      THREE_ALLOWANCE: '0',
      TYPE: '1',
      USE_Annual: '2',
      WEEKEND_ALLOWANCE: '0',
      WeekTime: '22',
      WeekType: '0',
      Week_START: '2021-01-01',
      YEAR: '',
      accident: '1',
      employment: '0',
      health: '0',
      images: [[Object]],
      insurance: '2',
      insurance_START: '2021-01-01',
      pension: '1',
      probation: '0',
      probationDATE: '2021-01-24T11:21:18.239Z',
      probationPercent: '',
      probationPeriod: '0',
    },
    resultdata: {CAL: '1', HELP: '도움말', MINPAY: '8,720'},
  },
];
