const i = [
  {
    CalendarEdit: 1,
    EMPCOUNT: 11,
    EMP_SEQ: 6058,
    IS_MANAGER: 1,
    OTHERPAY_SHOW: 1,
    PAY_SHOW: 1,
    STOREPAY_SHOW: '1',
    WORKFLAG: true,
    arba: 'https://www.gubgoo.com/event/cuRanding.html',
    arbashow: 0,
    arbashow2: 0,
    boardImage1:
      'https://wesop.s3.ap-northeast-2.amazonaws.com/shopsol/banner_owner.png',
    boardImage2:
      'https://wesop.s3.ap-northeast-2.amazonaws.com/shopsol/banner_worker.png',
    boardShow1: 0,
    boardShow2: 0,
    boardTitle1: '사업주 자유 게시판',
    boardTitle2: '직원 자유 게시판',
    boardUrl1: 'http://bit.ly/3kemsUJ',
    boardUrl2: 'http://bit.ly/3pL56zS',
    check_count: 4,
    checklength: 1,
    checklistshow: 1,
    emplist: 6,
    eventImage1:
      'https://wesop.s3.ap-northeast-2.amazonaws.com/shopsol/survey_event_02.jpg',
    eventImage2:
      'https://wesop.s3.ap-northeast-2.amazonaws.com/shopsol/survey_event_02.jpg',
    eventShow1: 1,
    eventShow2: 1,
    eventTitle1: '설문 EVENT',
    eventTitle2: '설문 EVENT',
    eventUrl1: 'https://wesopco.typeform.com/to/hTjMQJ9a',
    eventUrl2: 'https://wesopco.typeform.com/to/hTjMQJ9a',
    healthshow: 1,
    inviteemp: 0,
    menu: [0, 1, 2, 3, 4],
    noticelength: 64,
    noticeshow: 1,
    resultdata: {
      ADDR1: '서울 마포구 백범로 35 (신수동, 서강대학교)',
      ADDR2: '아루페관 302호',
      BN: '',
      CALCULATE_DAY: '1',
      CATEGORY: '기타',
      CEMU_EMP_NAME: null,
      CEMU_TYPE: null,
      CHECK_COUNT: 5,
      CLOSE_FLAG: '0',
      CREATE_TIME: '2021-03-06T07:30:56.000Z',
      CU_CODE: null,
      EARLY_FLAG: '0',
      EARLY_TIME: 0,
      EXPANSION: '0',
      FIRST: null,
      GPS: '1',
      H_CERT_DATE: null,
      H_CERT_FILE1: null,
      H_CERT_FILE2: null,
      H_CERT_NM: null,
      H_CERT_ORG_NM: null,
      H_TXAGNT_NO: null,
      JULI: 1000,
      LAT: '37.5514693075541',
      LATE_FLAG: '1',
      LATE_TIME: 10,
      LONG: '126.943024997981',
      MEMBER_SEQ: 11823,
      MEM_NAME: null,
      MEM_PHONE: null,
      NAME: '위솝',
      NAME2: 'ㅇㅅ',
      NEW_CEMU_SEQ: null,
      PAY_DAY: null,
      PWD: null,
      PWD2: null,
      QR: '/uploads/qr/4878.png',
      QRJULI: 0,
      QR_Num: 'wes10004',
      SCRAP: '0',
      STORE_NUM: null,
      STORE_SEQ: 4878,
      TAX_TYPE: null,
      TEL: '',
      TYPE: 1,
      ZIPCODE: null,
      createdAt: '2020-09-04 17:19:20',
      customMenu: '[0,1,2,3,4]',
      dong: '신수동',
      gu: '마포구',
      hasConfirmedQr: 1,
      other: '위솝',
      si: '서울',
      updatedAt: '2021-03-04 21:44:10',
    },
    resultmsg: '1',
    shelfLifeshow: 1,
    workinglist: 0,
  },
];
